tap "1password/tap"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/services"
tap "nshipster/formulae"
tap "pointfreeco/formulae"
tap "robotsandpencils/made"
tap "tuist/tuist"
tap "xcodesorg/made"
tap "keith/formulae"

brew "aria2"
brew "autoconf"
brew "automake"
brew "bat"
brew "chisel"
brew "cscope"
brew "ctags"
brew "diff-so-fancy"
brew "duti"
brew "exa"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "freetype"
brew "fzf"
brew "gdbm"
brew "gdk-pixbuf"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "git-flow"
brew "git-lfs"
brew "git-town"
brew "glab"
brew "glib"
brew "gmp"
brew "gnutls"
brew "graphviz"
brew "guile"
brew "harfbuzz"
brew "htop"
brew "icdiff"
brew "ideviceinstaller"
brew "imagemagick"
brew "jbig2dec"
brew "jpeg", link: true
brew "jq"
brew "keith/formulae/git-pile"
brew "lame"
brew "libass"
brew "libevent"
brew "libimobiledevice"
brew "libplist"
brew "libpng"
brew "librsvg"
brew "libssh2"
brew "libtasn1"
brew "libtiff"
brew "libtool"
brew "libusb"
brew "libusbmuxd"
brew "libzip"
brew "mas"
brew "mint"
brew "multimarkdown"
brew "ncdu"
brew "nmap"
brew "node"
brew "nshipster/formulae/xcderiveddata"
brew "p11-kit"
brew "pandoc"
brew "pango"
brew "pcre"
brew "peco"
brew "pkg-config"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "xcodesorg/made/xcodes"
brew "rsync"
brew "ruby"
brew "sphinx-doc"
brew "srt"
brew "ssh-copy-id"
brew "tcl-tk"
brew "tldr"
brew "tree"
brew "unbound"
brew "vim"
brew "wget"
brew "x264"
brew "xvid"
brew "xz"
brew "youtube-dl"
brew "zellij"

cask_args appdir: '/Applications'
cask "1password"
cask "1password-cli"
cask "arq"
cask "asset-catalog-tinkerer"
cask "bettertouchtool"
cask "brave-browser"
cask "chatology"
cask "cmake"
cask "coconutbattery"
cask "coderunner"
cask "dash"
cask "docker"
cask "drawio"
cask "figma"
cask "firefox"
cask "font-jetbrains-mono"
cask "ghostty"
cask "gitup"
cask "handbrake"
cask "hazel"
cask "istat-menus"
cask "iterm2"
cask "kaleidoscope"
cask "karabiner-elements"
cask "mailmate"
cask "marked"
cask "monodraw"
cask "moom"
cask "proxyman"
cask "shortcat"
cask "superduper"
cask "zoom"
cask 'keyboard-maestro'
cask 'launchbar'
cask 'provisioning'

mas "1Blocker", id: 1107421413
mas "Acorn", id: 1019272813
mas "Affinity Photo", id: 824183456
mas "Calcbot", id: 931657367
mas "Carbonize", id: 1451177988
mas "Copied", id: 1026349850
mas "Core Data Lab", id: 1460684638
mas "Deliveries", id: 924726344
mas "Diagrams", id: 1276248849
mas "Fantastical", id: 975937182
mas "GIF Brewery 3", id: 1081413713
mas "Gemini", id: 463541543
mas "iVI", id: 402279089
mas "Keynote", id: 409183694
mas "Mactracker", id: 430255202
mas "Max Inspect", id: 1438113612
mas "Next", id: 896146364
mas "Numbers", id: 409203825
mas "PCalc", id: 403504866
mas "Pages", id: 409201541
mas "Patterns", id: 429449079
mas "Pixa", id: 527618971
mas "PopClip", id: 445189367
mas "Project Statistics for Xcode", id: 650764572
mas "Quiver", id: 866773894
mas "ReadKit", id: 588726889
mas "Reeder", id: 1449412482
mas "SQLPro for SQLite", id: 586001240
mas "Shazam", id: 897118787
mas "ShotBox", id: 1278619270
mas "Side Mirror", id: 944860108
mas "Soulver", id: 413965349
mas "Spark", id: 1176895641
mas "StopTheMadness", id: 1376402589
mas "The Unarchiver", id: 425424353
mas "Theine", id: 955848755
mas "Things", id: 904280696
mas "iA Writer", id: 775737590
mas "iVI", id: 402279089
mas "xScope", id: 889428659
